Add repositories
Antiplusists/Cardsetta pull request #24
Opened 2021-04-27 08:55 UTC by Coll4pse

2021-04-27 09:06 UTC, scryptan commented on Core/Models/Dto/CreationCardDto.cs
> +        public byte[,]? Image { get; set; }
Ссылка на какой-то статик должна быть

2021-04-27 09:08 UTC, scryptan commented on Core/Models/Entities/NewDeckEntity.cs
> +        public NewDeckEntity(Guid authorId, string? imagePath, CreationDeckDto dto)
CreationDeckEntity?

2021-04-27 09:10 UTC, Coll4pse commented on Core/Models/Dto/CreationCardDto.cs
> +        public byte[,]? Image { get; set; }
Не ну в смысоле? Вообще там должен быть HttpPostedFileBase, бикос такая штука приходит с формы при загрузке файлов на сервер

2021-04-27 09:10 UTC, Coll4pse commented on Core/Models/Entities/NewDeckEntity.cs
> +        public NewDeckEntity(Guid authorId, string? imagePath, CreationDeckDto dto)
Maybe

2021-04-27 09:11 UTC, scryptan commented on Core/Repositories/Realizations/CardRepository.cs
> +            if (result is {State: EntityState.Deleted})
На эти условия надо тестов написать, я пока их не писал, возможно, что эти условия не работают

2021-04-27 09:14 UTC, scryptan reviewed
Понаписал комментов

2021-04-27 09:14 UTC, scryptan commented on Core/Repositories/Realizations/DeckRepository.cs
> +        public async Task<bool> AddCard(Guid deckId, CardDbo dbo)
Не стоит ли тут возвращать деку?

2021-04-27 09:14 UTC, scryptan commented on Core/Repositories/Realizations/DeckRepository.cs
> +        public async Task<bool> RemoveCard(Guid deckId, Guid cardId)
И тут?

2021-04-27 09:18 UTC, Coll4pse commented on Core/Repositories/Realizations/DeckRepository.cs
> +        public async Task<bool> AddCard(Guid deckId, CardDbo dbo)
Хороший вопрос

2021-04-27 09:19 UTC, scryptan commented on Core/Models/Dto/CreationCardDto.cs
> +        public byte[,]? Image { get; set; }
Перепутал, в дбошке точно должна быть ссылка на статик, а тут вообще не должно быть ничего, это надо либо на 2 запроса распилить, либо подумать как принимать multipart запросы

2021-05-04 05:40 UTC, scryptan requested changes

2021-05-04 05:40 UTC, scryptan commented on Core/Helpers/DropboxHelper.cs
> +}
Это, конечно, круто, но кажется надо было в отдельной ветке с отдельной задачкой

2021-05-04 05:40 UTC, scryptan commented on Core/Models/Dbo/DeckDbo.cs
> +        public string? ImagePath { get; set; }
Давай списки к спискам, остальные свойства друг с другом

2021-05-04 05:40 UTC, scryptan commented on Core/Startup.cs
> +            services.AddSingleton<TagRepository>();
О, а оно сразу вместо интерфейсов подставится?
Прост обычно используется <Interface, Realization> (или наоборот, не помню, но указывается под что подкладывать)

2021-05-11 11:07 UTC, merged